import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class MyRegisteredEvents extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyRegisteredEvents.class.getName());

    /**
     * Creates new form MyRegisteredEvents
     */
    private String studentName;
    public MyRegisteredEvents(String username) {
    initComponents();
    this.studentName = username; // Correctly stores the name passed to the constructor
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    loadMyData(); // Now this method can use the correct studentName
}
private void loadMyData() {
    // --- Load Registered Workshops ---
    String[] workshopColumns = {"Workshop Name", "Date Registered"};
    DefaultTableModel workshopTableModel = new DefaultTableModel(workshopColumns, 0);
    String workshopSql = "SELECT event_name, registration_date FROM registrations WHERE student_name = ?";

    try (Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement(workshopSql)) {

        pst.setString(1, studentName); // Use the student's name to filter

        try (ResultSet rs = pst.executeQuery()) {
            while(rs.next()) {
                Object[] row = {rs.getString("event_name"), rs.getString("registration_date")};
                workshopTableModel.addRow(row);
            }
        }
        RegisteredWorkshops.setModel(workshopTableModel); // Your table for workshops

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading your registered workshops.", "Database Error", JOptionPane.ERROR_MESSAGE);
    }

    // --- Load Registered Events ---
    String[] eventColumns = {"Event Name", "Date Registered"};
    DefaultTableModel eventTableModel = new DefaultTableModel(eventColumns, 0);
    String eventSql = "SELECT event_name, registration_date FROM event_registrations WHERE student_name = ?";
    
    try (Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement(eventSql)) {
        
        pst.setString(1, studentName); // Use the student's name again to filter
        
        try (ResultSet rs = pst.executeQuery()) {
            while(rs.next()) {
                Object[] row = {rs.getString("event_name"), rs.getString("registration_date")};
                eventTableModel.addRow(row);
            }
        }
        RegisteredEvents.setModel(eventTableModel); // Your table for events

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading your registered events.", "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RegisteredWorkshops = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        RegisteredEvents = new javax.swing.JTable();
        Events = new javax.swing.JLabel();
        workshop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 112));

        RegisteredWorkshops.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(RegisteredWorkshops);

        RegisteredEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(RegisteredEvents);

        Events.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        Events.setForeground(new java.awt.Color(255, 255, 255));
        Events.setText("Registered Events");

        workshop.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        workshop.setForeground(new java.awt.Color(255, 255, 255));
        workshop.setText("Registered Workshop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workshop, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                    .addComponent(Events, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(workshop, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Events, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyRegisteredEvents("Test Student").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Events;
    private javax.swing.JTable RegisteredEvents;
    private javax.swing.JTable RegisteredWorkshops;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel workshop;
    // End of variables declaration//GEN-END:variables
}
