/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mevin
 */
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
public class secondUpcomingEvents extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(secondUpcomingEvents.class.getName());

    /**
     * Creates new form secondUpcomingEvents
     */
    public secondUpcomingEvents() {
        initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Closes only this window
    loadEventsFromDB(); // Call the method to load events
    }
    /**
 * Fetches events from the database and creates a button for each one.
 */
/**
 * Fetches events from the database and creates a button for each one.
 */
private void loadEventsFromDB() {
    // Set layout and clear the correct panel
    eventspane1.setLayout(new GridLayout(0, 3, 10, 10)); // Use eventspane1
    eventspane1.removeAll(); // Use eventspane1

    String sql = "SELECT name, image_path FROM events ORDER BY id DESC";

    try (Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            String name = rs.getString("name");
            String imagePath = rs.getString("image_path");

            JButton eventButton = new JButton();
            eventButton.setText(name);

            try {
                ImageIcon icon = new ImageIcon(imagePath);
                Image img = icon.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH); 
                eventButton.setIcon(new ImageIcon(img));
            } catch (Exception e) {
                System.err.println("Could not load image: " + imagePath);
            }
            
            // Style the button
            eventButton.setVerticalTextPosition(SwingConstants.BOTTOM);
            eventButton.setHorizontalTextPosition(SwingConstants.CENTER);
            eventButton.setForeground(Color.WHITE); 
            eventButton.setFont(new Font("Segoe UI", Font.BOLD, 14));
            eventButton.setOpaque(false);
            eventButton.setContentAreaFilled(false);
            eventButton.setBorderPainted(false);
            eventButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

            // Add action listener
            eventButton.addActionListener(e -> {
                new RegisterEvent().setVisible(true); 
                this.dispose(); 
            });

            // Add the button to the correct panel
            eventspane1.add(eventButton); // Use eventspane1
        }

        // Refresh the correct panel
        eventspane1.revalidate(); // Use eventspane1
        eventspane1.repaint(); // Use eventspane1

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to load events from database.", "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanel1 = new javax.swing.JScrollPane();
        eventspane1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout eventspane1Layout = new javax.swing.GroupLayout(eventspane1);
        eventspane1.setLayout(eventspane1Layout);
        eventspane1Layout.setHorizontalGroup(
            eventspane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        eventspane1Layout.setVerticalGroup(
            eventspane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        jScrollPanel1.setViewportView(eventspane1);

        getContentPane().add(jScrollPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 85, -1, -1));

        backButton.setText("Back");
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 546, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Javanese Text", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Upcoming Events");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(517, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 790, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new secondUpcomingEvents().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel eventspane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPanel1;
    // End of variables declaration//GEN-END:variables
}
