/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mevin
 */
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
public class ViewWorkshopsForStudents extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewWorkshopsForStudents.class.getName());

    /**
     * Creates new form ViewWorkshopsForStudents
     */
    public ViewWorkshopsForStudents() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Close only this window
    loadWorkshopsFromDB(); // Call the method to load workshops
    }
/**
 * Fetches workshops from the database and creates a button for each one.
 */
private void loadWorkshopsFromDB() {
    // Set layout and clear the panel where buttons will go
    workshopPanel.setLayout(new GridLayout(0, 3, 15, 15)); // 3 columns, 15px spacing
    workshopPanel.removeAll(); 

    // SQL query to get data from the 'workshops' table
    String sql = "SELECT name, image_path FROM workshops ORDER BY id DESC";

    try (Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            String name = rs.getString("name");
            String imagePath = rs.getString("image_path");

            // Create button
            JButton workshopButton = new JButton();
            workshopButton.setText(name);

            // Load and set image icon
            try {
                ImageIcon icon = new ImageIcon(imagePath);
                Image img = icon.getImage().getScaledInstance(160, 160, Image.SCALE_SMOOTH); 
                workshopButton.setIcon(new ImageIcon(img));
            } catch (Exception e) {
                System.err.println("Could not load image: " + imagePath);
            }
            
            // Style the button
            workshopButton.setVerticalTextPosition(SwingConstants.BOTTOM);
            workshopButton.setHorizontalTextPosition(SwingConstants.CENTER);
            workshopButton.setForeground(Color.WHITE); 
            workshopButton.setFont(new Font("Segoe UI", Font.BOLD, 14));
            workshopButton.setOpaque(false);
            workshopButton.setContentAreaFilled(false);
            workshopButton.setBorderPainted(false);
            workshopButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
            workshopButton.setPreferredSize(new Dimension(180, 200)); 

            // Add action listener to open registration page
            workshopButton.addActionListener(e -> {
                new RegisterWorkshop().setVisible(true); 
                this.dispose(); 
            });

            // Add button to the panel
            workshopPanel.add(workshopButton);
        }

        // Refresh panel layout
        workshopPanel.revalidate();
        workshopPanel.repaint();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Failed to load workshops.", "Database Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workshopPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("\"Available Workshops");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 32, 206, -1));

        backButton.setText("Back");
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 550, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout workshopPanelLayout = new javax.swing.GroupLayout(workshopPanel);
        workshopPanel.setLayout(workshopPanelLayout);
        workshopPanelLayout.setHorizontalGroup(
            workshopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        workshopPanelLayout.setVerticalGroup(
            workshopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(workshopPanel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewWorkshopsForStudents().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel workshopPanel;
    // End of variables declaration//GEN-END:variables
}
